# Generated by Django 3.2 on 2023-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20230524_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personevent',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Error message'),
        ),
    ]
