name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build --sdist --wheel --outdir dist/ .

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      # Uncomment to publish to PyPI after validating on TestPyPI
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.8.14
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}

